language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gyp ninja-build binutils-gold
script:
  - CXXFLAGS=-O2 gyp -f ninja --depth=. ./dump_syms.gyp
  - ninja -C out/Default
os:
  - linux
notifications:
  email:
    - ted@mielczarek.org
