# Copied from https://github.com/springmeyer/hello-gyp/blob/master/appveyor.yml
platform:
#TODO: fix gyp file
#  - x64
  - x86

#TODO: fix gyp file
#configuration:
#  - Debug
#  - Release

install:
  - SET PATH=c:\python27;%PATH%
  - SET PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%
  - git clone --quiet --depth 1 https://chromium.googlesource.com/external/gyp.git gyp
  # note windows requires --generator-output to be absolute
  - python gyp/gyp_main.py dump_syms.gyp --depth=. -f msvs -G msvs_version=2013
  - set MSBUILD_PLATFORM=%platform%
  - if "%MSBUILD_PLATFORM%" == "x86" set MSBUILD_PLATFORM=Win32
  - msbuild dump_syms.sln /clp:Verbosity=minimal /nologo /p:Configuration=Default;Platform=%MSBUILD_PLATFORM%

build: OFF

test: OFF

test_script: OFF

deploy: OFF
